# Notebook created as a part of Capstone project

#### We simply use read_html method of pandas to obtain the list of tables from the wikipedia page.

In [128]:
import pandas as pd

df = pd.read_html("https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M")

In [129]:
df

[    Postcode           Borough  \
 0        M1A      Not assigned
 1        M2A      Not assigned
 2        M3A        North York
 3        M4A        North York
 4        M5A  Downtown Toronto
 5        M5A  Downtown Toronto
 6        M6A        North York
 7        M6A        North York
 8        M7A      Queen's Park
 9        M8A      Not assigned
 10       M9A         Etobicoke
 11       M1B       Scarborough
 12       M1B       Scarborough
 13       M2B      Not assigned
 14       M3B        North York
 15       M4B         East York
 16       M4B         East York
 17       M5B  Downtown Toronto
 18       M5B  Downtown Toronto
 19       M6B        North York
 20       M7B      Not assigned
 21       M8B      Not assigned
 22       M9B         Etobicoke
 23       M9B         Etobicoke
 24       M9B         Etobicoke
 25       M9B         Etobicoke
 26       M9B         Etobicoke
 27       M1C       Scarborough
 28       M1C       Scarborough
 29       M1C       Scarborough
 ..       ...               ...
 258      M9X      Not assigned
 259      M1Y      Not assigned
 260      M2Y      Not assigned
 261      M3Y      Not assigned
 262      M4Y  Downtown Toronto
 263      M5Y      Not assigned
 264      M6Y      Not assigned
 265      M7Y      East Toronto
 266      M8Y         Etobicoke
 267      M8Y         Etobicoke
 268      M8Y         Etobicoke
 269      M8Y         Etobicoke
 270      M8Y         Etobicoke
 271      M8Y         Etobicoke
 272      M8Y         Etobicoke
 273      M8Y         Etobicoke
 274      M9Y      Not assigned
 275      M1Z      Not assigned
 276      M2Z      Not assigned
 277      M3Z      Not assigned
 278      M4Z      Not assigned
 279      M5Z      Not assigned
 280      M6Z      Not assigned
 281      M7Z      Not assigned
 282      M8Z         Etobicoke
 283      M8Z         Etobicoke
 284      M8Z         Etobicoke
 285      M8Z         Etobicoke
 286      M8Z         Etobicoke
 287      M9Z      Not assigned

                                          Neighbourhood
 0                                         Not assigned
 1                                         Not assigned
 2                                            Parkwoods
 3                                     Victoria Village
 4                                         Harbourfront
 5                                          Regent Park
 6                                     Lawrence Heights
 7                                       Lawrence Manor
 8                                         Not assigned
 9                                         Not assigned
 10                                    Islington Avenue
 11                                               Rouge
 12                                             Malvern
 13                                        Not assigned
 14                                     Don Mills North
 15                                    Woodbine Gardens
 16                                       Parkview Hill
 17                                             Ryerson
 18                                     Garden District
 19                                           Glencairn
 20                                        Not assigned
 21                                        Not assigned
 22                                          Cloverdale
 23                                           Islington
 24                                        Martin Grove
 25                                    Princess Gardens
 26                                     West Deane Park
 27                                      Highland Creek
 28                                          Rouge Hill
 29                                          Port Union
 ..                                                 ...
 258                                       Not assigned
 259                                       Not assigned
 260                                       Not assigned
 261                                       Not assigned
 262                               Church and Wellesley
 263                                       Not assigned
 264                                       Not assigned
 265  Business Reply Mail Processing Centre 969 Eastern
 266                                         Humber Bay
 267                                   King's Mill Park
 268                           Kingsway Park South East
 269                                          Mimico NE
 270                                     Old Mill South
 271                                 The Queensway East
 272                              Royal York South East
 273                                           Sunnylea
 274                                       Not assigned
 275                                       Not assigned
 276                                       Not assigned
 277                                       Not assigned
 278                                       Not assigned
 279                                       Not assigned
 280                                       Not assigned
 281                                       Not assigned
 282                           Kingsway Park South West
 283                                          Mimico NW
 284                                 The Queensway West
 285                              Royal York South West
 286                                     South of Bloor
 287                                       Not assigned

 [288 rows x 3 columns],
                                                   0   \
 0                                                NaN
 1  NL NS PE NB QC ON MB SK AB BC NU/NT YT A B C E...
 2                                                 NL
 3                                                  A

                                                   1   \
 0                              Canadian postal codes
 1  NL NS PE NB QC ON MB SK AB BC NU/NT YT A B C E...
 2                                                 NS
 3                                                  B

                                                   2    3    4    5    6    7   \
 0                                                NaN  NaN  NaN  NaN  NaN  NaN
 1  NL NS PE NB QC ON MB SK AB BC NU/NT YT A B C E...  NaN  NaN  NaN  NaN  NaN
 2                                                 PE   NB   QC   QC   QC   ON
 3                                                  C    E    G    H    J    K

     8    9    10   11   12   13   14   15     16   17
 0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    NaN  NaN
 1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    NaN  NaN
 2   ON   ON   ON   ON   MB   SK   AB   BC  NU/NT   YT
 3    L    M    N    P    R    S    T    V      X    Y  ,
    0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15     16  17
 0  NL  NS  PE  NB  QC  QC  QC  ON  ON  ON  ON  ON  MB  SK  AB  BC  NU/NT  YT
 1   A   B   C   E   G   H   J   K   L   M   N   P   R   S   T   V      X   Y]

#### We only require the first table in the list, so we extract it.

In [130]:
df = df[0]
df.head()

  Postcode           Borough     Neighbourhood
0      M1A      Not assigned      Not assigned
1      M2A      Not assigned      Not assigned
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront

#### Then we remove the cells in which Borough is not assigned

In [131]:
df = df[df['Borough'] != 'Not assigned']

In [132]:
df.head()

  Postcode           Borough     Neighbourhood
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront
5      M5A  Downtown Toronto       Regent Park
6      M6A        North York  Lawrence Heights

#### Resetting indices

In [133]:
df.reset_index(drop=True, inplace=True)

In [134]:
df.head()

  Postcode           Borough     Neighbourhood
0      M3A        North York         Parkwoods
1      M4A        North York  Victoria Village
2      M5A  Downtown Toronto      Harbourfront
3      M5A  Downtown Toronto       Regent Park
4      M6A        North York  Lawrence Heights

#### Appending lists of neighborhoods together requires us to iterate through the whole dataframe. If the postal code is repeated, instead of inserting a new row into our new dataframe, we append the new neighbourhood value to the neighbourhood value of the last row of the new dataframe

In [135]:
df2 = pd.DataFrame({'PostalCode': [df.loc[0]['Postcode']], 'Borough': [df.loc[0]['Borough']], 'Neighbourhood': [df.loc[0]['Neighbourhood']]})

In [136]:
i = 1
while i<df.shape[0]:
    if df.loc[i]['Postcode'] != df.loc[i-1]['Postcode']:
        
        df3 = {'PostalCode': df.loc[i]['Postcode'], 'Borough': df.loc[i]['Borough'], 'Neighbourhood': df.loc[i]['Neighbourhood']}
        df2 = df2.append(df3, ignore_index=True)
    else:
        df2.loc[df2.shape[0]-1]['Neighbourhood'] += ", " + df.loc[i]['Neighbourhood']
    i += 1

#### We check if the code is successful by displaying the entire dataframe

In [137]:
df2.head(df2.shape[0])

,PostalCode,Borough,Neighbourhood
0,M3A,North York,Parkwoods
1,M4A,North York,Victoria Village
2,M5A,Downtown Toronto,"Harbourfront, Regent Park"
3,M6A,North York,"Lawrence Heights, Lawrence Manor"
4,M7A,Queen's Park,Not assigned
5,M9A,Etobicoke,Islington Avenue
6,M1B,Scarborough,"Rouge, Malvern"
7,M3B,North York,Don Mills North
8,M4B,East York,"Woodbine Gardens, Parkview Hill"
9,M5B,Downtown Toronto,"Ryerson, Garden District"
10,M6B,North York,Glencairn
11,M9B,Etobicoke,"Cloverdale, Islington, Martin Grove, Princess ..."
12,M1C,Scarborough,"Highland Creek, Rouge Hill, Port Union"
13,M3C,North York,"Flemingdon Park, Don Mills South"
14,M4C,East York,Woodbine Heights
15,M5C,Downtown Toronto,St. James Town
16,M6C,York,Humewood-Cedarvale
17,M9C,Etobicoke,"Bloordale Gardens, Eringate, Markland Wood, Ol..."
18,M1E,Scarborough,"Guildwood, Morningside, West Hill"
19,M4E,East Toronto,The Beaches
20,M5E,Downtown Toronto,Berczy Park
21,M6E,York,Caledonia-Fairbanks
22,M1G,Scarborough,Woburn
23,M4G,East York,Leaside
24,M5G,Downtown Toronto,Central Bay Street
25,M6G,Downtown Toronto,Christie
26,M1H,Scarborough,Cedarbrae
27,M2H,North York,Hillcrest Village
28,M3H,North York,"Bathurst Manor, Downsview North, Wilson Heights"
29,M4H,East York,Thorncliffe Park
...,...,...,...
73,M4R,Central Toronto,North Toronto West
74,M5R,Central Toronto,"The Annex, North Midtown, Yorkville"
75,M6R,West Toronto,"Parkdale, Roncesvalles"
76,M7R,Mississauga,Canada Post Gateway Processing Centre
77,M9R,Etobicoke,"Kingsview Village, Martin Grove Gardens, Richv..."
78,M1S,Scarborough,Agincourt
79,M4S,Central Toronto,Davisville
80,M5S,Downtown Toronto,"Harbord, University of Toronto"
81,M6S,West Toronto,"Runnymede, Swansea"
82,M1T,Scarborough,"Clarks Corners, Sullivan, Tam O'Shanter"
83,M4T,Central Toronto,"Moore Park, Summerhill East"
84,M5T,Downtown Toronto,"Chinatown, Grange Park, Kensington Market"
85,M1V,Scarborough,"Agincourt North, L'Amoreaux East, Milliken, St..."
86,M4V,Central Toronto,"Deer Park, Forest Hill SE, Rathnelly, South Hi..."
87,M5V,Downtown Toronto,"CN Tower, Bathurst Quay, Island airport, Harbo..."
88,M8V,Etobicoke,"Humber Bay Shores, Mimico South, New Toronto"
89,M9V,Etobicoke,"Albion Gardens, Beaumond Heights, Humbergate, ..."
90,M1W,Scarborough,L'Amoreaux West
91,M4W,Downtown Toronto,Rosedale
92,M5W,Downtown Toronto,Stn A PO Boxes 25 The Esplanade
93,M8W,Etobicoke,"Alderwood, Long Branch"
94,M9W,Etobicoke,Northwest
95,M1X,Scarborough,Upper Rouge
96,M4X,Downtown Toronto,"Cabbagetown, St. James Town"
97,M5X,Downtown Toronto,"First Canadian Place, Underground city"
98,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
99,M4Y,Downtown Toronto,Church and Wellesley
100,M7Y,East Toronto,Business Reply Mail Processing Centre 969 Eastern
101,M8Y,Etobicoke,"Humber Bay, King's Mill Park, Kingsway Park So..."
102,M8Z,Etobicoke,"Kingsway Park South West, Mimico NW, The Queen..."

In [138]:
df = df2

#### If the value of Neighbourhood is not assigned, we assign the value of neighbourhood to it.

In [139]:
df.loc[df['Neighbourhood'] == 'Not assigned', 'Neighbourhood'] = df[df['Neighbourhood'] == 'Not assigned']['Borough']

In [140]:
df.head()

  PostalCode           Borough                     Neighbourhood
0        M3A        North York                         Parkwoods
1        M4A        North York                  Victoria Village
2        M5A  Downtown Toronto         Harbourfront, Regent Park
3        M6A        North York  Lawrence Heights, Lawrence Manor
4        M7A      Queen's Park                      Queen's Park

In [141]:
df.shape

(103, 3)

In [150]:
df2 = pd.read_csv('Geospatial_Coordinates.csv')
df2['PostalCode'] = df2['Postal Code']
df2 = df2[['PostalCode', 'Latitude', 'Longitude']]

In [151]:
df2.head()

  PostalCode   Latitude  Longitude
0        M1B  43.806686 -79.194353
1        M1C  43.784535 -79.160497
2        M1E  43.763573 -79.188711
3        M1G  43.770992 -79.216917
4        M1H  43.773136 -79.239476

In [152]:
df = pd.merge(df, df2, on='PostalCode')

In [153]:
df.head()

,PostalCode,Borough,Neighbourhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.753259,-79.329656
1,M4A,North York,Victoria Village,43.725882,-79.315572
2,M5A,Downtown Toronto,"Harbourfront, Regent Park",43.654260,-79.360636
3,M6A,North York,"Lawrence Heights, Lawrence Manor",43.718518,-79.464763
4,M7A,Queen's Park,Queen's Park,43.662301,-79.389494